//! `skills/*` codecs. Field, enum and nullable handling follows the schema
//! generated by the pinned CLI; unknown JSON is retained, never re-derived.

use anyhow::{Context as _, Result, bail};
use serde_json::{Map, Value};

use crate::agent::{
    AgentSkill, AgentSkillDependency, AgentSkillInterface, AgentSkillLoadError, AgentSkillScope,
    AgentSkillSelector, AgentSkillWriteReceipt, AgentSkillsEntry, AgentSkillsSnapshot,
};

const METHOD_LIST: &str = "skills/list";
const METHOD_WRITE: &str = "skills/config/write";

pub(super) fn list_params(cwds: &[std::path::PathBuf], force_reload: bool) -> Value {
    let cwds = cwds
        .iter()
        .map(|cwd| Value::String(cwd.display().to_string()))
        .collect::<Vec<_>>();
    // Empty `cwds` is the documented request for the session default; the
    // client omits the key instead of sending an explicitly empty list.
    let mut params = Map::new();
    if !cwds.is_empty() {
        params.insert("cwds".into(), Value::Array(cwds));
    }
    if force_reload {
        params.insert("forceReload".into(), Value::Bool(true));
    }
    Value::Object(params)
}

pub(super) fn write_params(selector: &AgentSkillSelector, enabled: bool) -> Value {
    // Only the selector the user acted on and the requested flag are sent;
    // nullable selector fields stay absent rather than being sent as null.
    let mut params = Map::new();
    params.insert("enabled".into(), Value::Bool(enabled));
    match selector {
        AgentSkillSelector::Name(name) => {
            params.insert("name".into(), Value::String(name.clone()));
        }
        AgentSkillSelector::Path(path) => {
            params.insert("path".into(), Value::String(path.display().to_string()));
        }
    }
    Value::Object(params)
}

fn unknown_fields(object: &Map<String, Value>, known: &[&str]) -> Map<String, Value> {
    object
        .iter()
        .filter(|(key, _)| !known.contains(&key.as_str()))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect()
}

fn required_string(object: &Map<String, Value>, field: &str, context: &str) -> Result<String> {
    object
        .get(field)
        .and_then(Value::as_str)
        .map(str::to_owned)
        .with_context(|| format!("{context} 缺少字符串字段 {field}"))
}

fn required_bool(object: &Map<String, Value>, field: &str, context: &str) -> Result<bool> {
    object
        .get(field)
        .and_then(Value::as_bool)
        .with_context(|| format!("{context} 缺少布尔字段 {field}"))
}

fn optional_string(
    object: &Map<String, Value>,
    field: &str,
    context: &str,
) -> Result<Option<String>> {
    match object.get(field) {
        None | Some(Value::Null) => Ok(None),
        Some(Value::String(value)) => Ok(Some(value.clone())),
        Some(_) => bail!("{context} 的 {field} 必须是字符串或 null"),
    }
}

fn optional_path(
    object: &Map<String, Value>,
    field: &str,
    context: &str,
) -> Result<Option<std::path::PathBuf>> {
    Ok(optional_string(object, field, context)?.map(std::path::PathBuf::from))
}

fn object<'a>(value: &'a Value, context: &str) -> Result<&'a Map<String, Value>> {
    value
        .as_object()
        .with_context(|| format!("{context} 必须是 JSON 对象"))
}

fn interface(value: &Value) -> Result<AgentSkillInterface> {
    const KNOWN: &[&str] = &[
        "displayName",
        "shortDescription",
        "defaultPrompt",
        "brandColor",
        "iconSmall",
        "iconLarge",
        "iconSmallUrl",
        "iconLargeUrl",
    ];
    let fields = object(value, "skills/list 的 interface")?;
    Ok(AgentSkillInterface {
        display_name: optional_string(fields, "displayName", "interface")?,
        short_description: optional_string(fields, "shortDescription", "interface")?,
        default_prompt: optional_string(fields, "defaultPrompt", "interface")?,
        brand_color: optional_string(fields, "brandColor", "interface")?,
        icon_small: optional_path(fields, "iconSmall", "interface")?,
        icon_large: optional_path(fields, "iconLarge", "interface")?,
        icon_small_url: optional_string(fields, "iconSmallUrl", "interface")?,
        icon_large_url: optional_string(fields, "iconLargeUrl", "interface")?,
        extra: unknown_fields(fields, KNOWN).into_iter().collect(),
    })
}

fn dependency(value: &Value) -> Result<AgentSkillDependency> {
    const KNOWN: &[&str] = &[
        "type",
        "value",
        "command",
        "description",
        "transport",
        "url",
    ];
    let fields = object(value, "skills/list 的 dependencies.tools")?;
    Ok(AgentSkillDependency {
        tool_type: required_string(fields, "type", "skill dependency")?,
        value: required_string(fields, "value", "skill dependency")?,
        command: optional_string(fields, "command", "skill dependency")?,
        description: optional_string(fields, "description", "skill dependency")?,
        transport: optional_string(fields, "transport", "skill dependency")?,
        url: optional_string(fields, "url", "skill dependency")?,
        extra: unknown_fields(fields, KNOWN).into_iter().collect(),
    })
}

fn skill(value: &Value) -> Result<AgentSkill> {
    const KNOWN: &[&str] = &[
        "name",
        "description",
        "path",
        "scope",
        "enabled",
        "shortDescription",
        "pluginId",
        "interface",
        "dependencies",
    ];
    let fields = object(value, "skills/list 的 skill")?;
    let raw_scope = required_string(fields, "scope", "skill")?;
    let scope = AgentSkillScope::parse(&raw_scope)
        .with_context(|| format!("skills/list 的 skill.scope 为未知值 `{raw_scope}`"))?;
    let dependencies = match fields.get("dependencies") {
        None | Some(Value::Null) => None,
        Some(value) => {
            let dependencies = object(value, "skill.dependencies")?;
            let tools = dependencies
                .get("tools")
                .context("skill.dependencies 缺少 tools")?
                .as_array()
                .context("skill.dependencies.tools 必须是数组")?;
            Some(tools.iter().map(dependency).collect::<Result<Vec<_>>>()?)
        }
    };
    Ok(AgentSkill {
        name: required_string(fields, "name", "skill")?,
        description: required_string(fields, "description", "skill")?,
        path: std::path::PathBuf::from(required_string(fields, "path", "skill")?),
        scope,
        enabled: required_bool(fields, "enabled", "skill")?,
        short_description: optional_string(fields, "shortDescription", "skill")?,
        plugin_id: optional_string(fields, "pluginId", "skill")?,
        interface: match fields.get("interface") {
            None | Some(Value::Null) => None,
            Some(value) => Some(interface(value)?),
        },
        dependencies,
        extra: unknown_fields(fields, KNOWN).into_iter().collect(),
    })
}

fn load_error(value: &Value) -> Result<AgentSkillLoadError> {
    const KNOWN: &[&str] = &["path", "message"];
    let fields = object(value, "skills/list 的 errors")?;
    Ok(AgentSkillLoadError {
        path: std::path::PathBuf::from(required_string(fields, "path", "skill error")?),
        message: required_string(fields, "message", "skill error")?,
        extra: unknown_fields(fields, KNOWN).into_iter().collect(),
    })
}

pub(super) fn decode_snapshot(generation: u64, value: &Value) -> Result<AgentSkillsSnapshot> {
    const KNOWN: &[&str] = &["data", "nextCursor"];
    let fields = object(value, &format!("{METHOD_LIST} 响应"))?;
    let data = fields
        .get("data")
        .context("skills/list 响应缺少 data")?
        .as_array()
        .context("skills/list 响应的 data 必须是数组")?;
    let mut entries = Vec::with_capacity(data.len());
    for entry in data {
        let entry = object(entry, "skills/list 的 data 项")?;
        let skills = entry
            .get("skills")
            .context("skills/list 的 data 项缺少 skills")?
            .as_array()
            .context("skills/list 的 skills 必须是数组")?;
        let errors = entry
            .get("errors")
            .context("skills/list 的 data 项缺少 errors")?
            .as_array()
            .context("skills/list 的 errors 必须是数组")?;
        entries.push(AgentSkillsEntry {
            cwd: std::path::PathBuf::from(required_string(entry, "cwd", "skills/list entry")?),
            skills: skills.iter().map(skill).collect::<Result<Vec<_>>>()?,
            errors: errors.iter().map(load_error).collect::<Result<Vec<_>>>()?,
            extra: unknown_fields(entry, &["cwd", "skills", "errors"])
                .into_iter()
                .collect(),
        });
    }
    Ok(AgentSkillsSnapshot {
        generation,
        entries,
        next_cursor: optional_string(fields, "nextCursor", METHOD_LIST)?,
        extra: unknown_fields(fields, KNOWN).into_iter().collect(),
    })
}

pub(super) fn decode_write_receipt(value: &Value) -> Result<AgentSkillWriteReceipt> {
    const KNOWN: &[&str] = &["effectiveEnabled"];
    let fields = object(value, &format!("{METHOD_WRITE} 响应"))?;
    Ok(AgentSkillWriteReceipt {
        effective_enabled: required_bool(fields, "effectiveEnabled", METHOD_WRITE)?,
        extra: unknown_fields(fields, KNOWN).into_iter().collect(),
    })
}

/// `skills/changed` is an invalidation signal: the schema defines no payload
/// this client may act on, and an unexpected shape is a protocol error.
pub(super) fn parse_changed(message: &Value) -> Result<()> {
    match message.get("params") {
        None | Some(Value::Null) => Ok(()),
        Some(Value::Object(_)) => Ok(()),
        Some(_) => bail!("skills/changed 的 params 必须是对象或 null"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn list_params_omit_defaults_and_keep_force_reload() {
        assert_eq!(list_params(&[], false), json!({}));
        assert_eq!(list_params(&[], true), json!({"forceReload": true}));
        assert_eq!(
            list_params(&[std::path::PathBuf::from("/tmp/project")], false),
            json!({"cwds": ["/tmp/project"]})
        );
    }

    #[test]
    fn write_params_send_only_the_acted_on_selector() {
        assert_eq!(
            write_params(&AgentSkillSelector::Name("plugin:skill".into()), false),
            json!({"enabled": false, "name": "plugin:skill"})
        );
        assert_eq!(
            write_params(
                &AgentSkillSelector::Path(std::path::PathBuf::from("/skills/a/SKILL.md")),
                true
            ),
            json!({"enabled": true, "path": "/skills/a/SKILL.md"})
        );
    }

    #[test]
    fn snapshot_decode_keeps_extensions_and_requires_known_scope() {
        let snapshot = decode_snapshot(
            4,
            &json!({
                "data": [{
                    "cwd": "/tmp/project",
                    "skills": [{
                        "name": "release-notes",
                        "description": "d",
                        "path": "/skills/release-notes/SKILL.md",
                        "scope": "user",
                        "enabled": true,
                        "shortDescription": "short",
                        "pluginId": null,
                        "interface": {"displayName": "Release Notes", "futureFlag": 1},
                        "dependencies": {"tools": [{"type": "mcp", "value": "echo", "url": "https://x"}]},
                        "extension": "kept",
                    }],
                    "errors": [{"path": "/skills/broken/SKILL.md", "message": "bad front matter"}],
                    "entryExtension": true,
                }],
                "nextCursor": null,
                "snapshotExtension": 5,
            }),
        )
        .unwrap();
        assert_eq!(snapshot.generation, 4);
        assert_eq!(snapshot.next_cursor, None);
        assert_eq!(snapshot.extra["snapshotExtension"], json!(5));
        let entry = &snapshot.entries[0];
        assert_eq!(entry.extra["entryExtension"], json!(true));
        assert_eq!(entry.errors.len(), 1);
        let skill = &entry.skills[0];
        assert_eq!(skill.scope, AgentSkillScope::User);
        assert_eq!(skill.extra["extension"], json!("kept"));
        assert_eq!(
            skill.interface.as_ref().unwrap().extra["futureFlag"],
            json!(1)
        );
        assert_eq!(
            skill.dependencies.as_ref().unwrap()[0].url.as_deref(),
            Some("https://x")
        );
        assert_eq!(
            skill.selector(),
            AgentSkillSelector::Path("/skills/release-notes/SKILL.md".into())
        );

        let mut unknown = json!({"data": []});
        unknown["data"] = json!([{
            "cwd": "/tmp",
            "skills": [{"name": "x", "description": "d", "path": "/p", "scope": "teams", "enabled": true}],
            "errors": []
        }]);
        assert!(decode_snapshot(1, &unknown).is_err());
    }

    #[test]
    fn receipt_decode_requires_the_effective_value() {
        let receipt =
            decode_write_receipt(&json!({"effectiveEnabled": false, "note": "x"})).unwrap();
        assert!(!receipt.effective_enabled);
        assert_eq!(receipt.extra["note"], json!("x"));
        assert!(decode_write_receipt(&json!({})).is_err());
    }

    #[test]
    fn changed_notification_is_an_invalidation_signal() {
        assert!(parse_changed(&json!({"method": "skills/changed", "params": {}})).is_ok());
        assert!(parse_changed(&json!({"method": "skills/changed"})).is_ok());
        assert!(parse_changed(&json!({"method": "skills/changed", "params": 3})).is_err());
    }
}
