//! Conversation state owned independently of the GPUI input view.

use std::{collections::HashMap, path::PathBuf};

use super::{
    activity::ConversationActivity,
    transcript::{ConversationPhase, ConversationTranscriptTurn, ResumedTurnPresentation},
};
use crate::agent::{
    AgentApprovalHandle, AgentCommandApprovalRequest, AgentConnectionEvent,
    AgentEffectivePermissions, AgentFileApprovalHandle, AgentFileChange, AgentInterruptHandle,
    AgentMcpElicitationHandle, AgentMcpElicitationIdentity, AgentMcpServerStartupStatus,
    AgentModel, AgentPermissionsApprovalHandle, AgentServerRequestMetadata, AgentThreadStatus,
    AgentThreadTokenUsage, AgentUserInputHandle, ProjectId,
};

pub(crate) struct ConversationState {
    pub(crate) runtime: crate::agent::AgentRuntimeState,
    pub(crate) retired_runtime: Vec<crate::agent::AgentRuntimeState>,
    pub(crate) deprecation_notices: Vec<crate::agent::AgentDeprecationNotice>,
    pub(crate) user_message: Option<String>,
    pub(crate) user_images: Vec<crate::agent::UserMessageAttachment>,
    pub(crate) user_message_time: Option<String>,
    pub(crate) assistant_message: String,
    pub(crate) activities: Vec<ConversationActivity>,
    pub(crate) assistant_message_time: Option<String>,
    pub(crate) phase: ConversationPhase,
    pub(crate) transcript: Vec<ConversationTranscriptTurn>,
    pub(crate) resumed_turn: Option<ResumedTurnPresentation>,
    pub(crate) assistant_message_phases: HashMap<String, Option<String>>,
    pub(crate) cwd: PathBuf,
    pub(crate) project_id: Option<ProjectId>,
    pub(crate) history_loading: bool,
    pub(crate) history_error: Option<String>,
    /// Set when a revert this client did not request invalidated the locally
    /// reduced turns; the host reloads them from app-server.
    pub(crate) history_stale: bool,
    /// Turn currently being rewritten by the composer's edit mode.
    pub(crate) message_edit_turn_id: Option<String>,
    pub(crate) cycle: u64,
    pub(crate) turn_identity: Option<crate::agent::AgentTurnIdentity>,
    pub(crate) submissions: Vec<super::UserSubmission>,
    pub(crate) seen_user_items: std::collections::HashSet<String>,
    pub(crate) active_turn: Option<AgentInterruptHandle>,
    pub(crate) pending_connection_events: HashMap<String, Vec<AgentConnectionEvent>>,
    pub(crate) pending_review_events: HashMap<String, Vec<crate::agent::AgentEvent>>,
    pub(crate) approval_responders: HashMap<String, AgentApprovalHandle>,
    pub(crate) command_approval_requests: HashMap<String, AgentCommandApprovalRequest>,
    pub(crate) file_approval_responders: HashMap<String, AgentFileApprovalHandle>,
    pub(crate) file_changes: HashMap<String, AgentFileChange>,
    pub(crate) user_input_responders: HashMap<String, AgentUserInputHandle>,
    pub(crate) permissions_approval_responders: HashMap<String, AgentPermissionsApprovalHandle>,
    /// Elicitation responders are keyed by connection generation plus the
    /// original request id, never by the current turn.
    pub(crate) mcp_elicitation_responders: HashMap<String, AgentMcpElicitationHandle>,
    pub(crate) mcp_elicitation_contexts: HashMap<String, AgentMcpElicitationIdentity>,
    pub(crate) server_request_contexts: HashMap<String, AgentServerRequestMetadata>,
    pub(crate) thread_id: Option<String>,
    pub(crate) turn_id: Option<String>,
    pub(crate) mcp_server_startup_statuses:
        HashMap<(Option<String>, String), AgentMcpServerStartupStatus>,
    pub(crate) thread_statuses: HashMap<String, AgentThreadStatus>,
    pub(crate) thread_token_usages: HashMap<String, AgentThreadTokenUsage>,
    pub(crate) models: Vec<AgentModel>,
    pub(crate) model_catalog_error: Option<String>,
    pub(crate) model_user_selected: bool,
    pub(crate) plan_default_effort: Option<String>,
    pub(crate) selected_model: String,
    pub(crate) selected_effort: String,
    pub(crate) selected_service_tier: Option<String>,
    pub(crate) actual_model: Option<String>,
    pub(crate) model_status: Option<String>,
    pub(crate) safety_buffering: bool,
    pub(crate) slider_index: usize,
    pub(crate) effective_permissions: Option<AgentEffectivePermissions>,
    pub(crate) permission_change: Option<super::PermissionChange>,
    pub(crate) permission_error: Option<String>,
}

impl Default for ConversationState {
    fn default() -> Self {
        Self {
            runtime: Default::default(),
            retired_runtime: Vec::new(),
            deprecation_notices: Vec::new(),
            user_message: None,
            user_images: Vec::new(),
            user_message_time: None,
            assistant_message: String::new(),
            activities: Vec::new(),
            assistant_message_time: None,
            phase: ConversationPhase::Empty,
            transcript: Vec::new(),
            resumed_turn: None,
            assistant_message_phases: HashMap::new(),
            cwd: std::env::current_dir().unwrap_or_default(),
            project_id: None,
            history_loading: false,
            history_error: None,
            history_stale: false,
            message_edit_turn_id: None,
            cycle: 0,
            turn_identity: None,
            submissions: Vec::new(),
            seen_user_items: Default::default(),
            active_turn: None,
            pending_connection_events: HashMap::new(),
            pending_review_events: HashMap::new(),
            approval_responders: HashMap::new(),
            command_approval_requests: HashMap::new(),
            file_approval_responders: HashMap::new(),
            file_changes: HashMap::new(),
            user_input_responders: HashMap::new(),
            permissions_approval_responders: HashMap::new(),
            mcp_elicitation_responders: HashMap::new(),
            mcp_elicitation_contexts: HashMap::new(),
            server_request_contexts: HashMap::new(),
            thread_id: None,
            turn_id: None,
            mcp_server_startup_statuses: HashMap::new(),
            thread_statuses: HashMap::new(),
            thread_token_usages: HashMap::new(),
            models: Vec::new(),
            model_catalog_error: None,
            model_user_selected: false,
            plan_default_effort: None,
            selected_model: String::new(),
            selected_effort: String::new(),
            selected_service_tier: None,
            actual_model: None,
            model_status: None,
            safety_buffering: false,
            slider_index: 0,
            effective_permissions: None,
            permission_change: None,
            permission_error: None,
        }
    }
}
