//! Computer use settings presentation.

use gpui::{Context, IntoElement, div, prelude::*, px};

use super::SettingsView;
use crate::{settings::PageSpec, theme::Theme};

impl SettingsView {
    pub(super) fn computer_use_content(
        &self,
        page: &'static PageSpec,
        theme: Theme,
        cx: &mut Context<Self>,
    ) -> gpui::AnyElement {
        let rows = page.sections[0].rows;
        let extension_badge = || {
            div()
                .absolute()
                .right(px(-1.0))
                .bottom(px(-1.0))
                .size(px(16.0))
                .rounded(px(4.5))
                .border_1()
                .border_color(gpui::rgba(0xa6a8aaff))
                .bg(gpui::white())
                .child(
                    div()
                        .absolute()
                        .left(px(-2.0))
                        .top(px(5.0))
                        .size(px(5.0))
                        .rounded_full()
                        .border_1()
                        .border_color(gpui::rgba(0xa6a8aaff))
                        .bg(gpui::white()),
                )
        };
        let mut apps = div()
            .mt(px(16.5))
            .rounded(px(20.0))
            .overflow_hidden()
            .border_1()
            .border_color(theme.border)
            .bg(theme.settings_panel);
        for (index, row) in rows[..4].iter().enumerate() {
            let icon = match index {
                0 => div()
                    .size(px(40.0))
                    .rounded(px(8.0))
                    .overflow_hidden()
                    .relative()
                    .border_1()
                    .border_color(theme.border)
                    .bg(theme.settings_panel)
                    .child(
                        div()
                            .absolute()
                            .left(px(2.0))
                            .top(px(2.0))
                            .size(px(16.0))
                            .rounded(px(1.5))
                            .border_1()
                            .border_color(gpui::rgba(0xa9a9a9ff))
                            .bg(gpui::rgba(0xf3f3f3ff))
                            .child(
                                div()
                                    .absolute()
                                    .left(px(3.0))
                                    .top(px(3.0))
                                    .size(px(3.0))
                                    .rounded_full()
                                    .bg(gpui::rgba(0x4e89d8ff)),
                            )
                            .child(
                                div()
                                    .absolute()
                                    .left(px(2.0))
                                    .top(px(9.0))
                                    .w(px(11.0))
                                    .h(px(4.0))
                                    .rounded(px(1.0))
                                    .bg(gpui::rgba(0x6baa45ff)),
                            ),
                    )
                    .child(
                        div()
                            .absolute()
                            .left(px(2.0))
                            .top(px(17.0))
                            .text_size(px(14.0))
                            .line_height(px(20.0))
                            .font_weight(gpui::FontWeight::NORMAL)
                            .child("Compu"),
                    )
                    .into_any_element(),
                1 => div()
                    .size(px(40.0))
                    .rounded(px(8.0))
                    .overflow_hidden()
                    .relative()
                    .border_1()
                    .border_color(theme.border)
                    .child(gpui::img("icons/settings-computer-chrome.svg").size_full())
                    .child(extension_badge())
                    .into_any_element(),
                2 => div()
                    .size(px(40.0))
                    .rounded(px(8.0))
                    .overflow_hidden()
                    .border_1()
                    .border_color(theme.border)
                    .child(gpui::img("icons/settings-computer-edge.svg").size_full())
                    .into_any_element(),
                _ => div()
                    .size(px(40.0))
                    .rounded(px(8.0))
                    .overflow_hidden()
                    .relative()
                    .border_1()
                    .border_color(theme.border)
                    .bg(theme.settings_panel)
                    .child(
                        div()
                            .absolute()
                            .left(px(14.0))
                            .top(px(5.0))
                            .w(px(20.0))
                            .h(px(30.0))
                            .rounded(px(2.0))
                            .border_1()
                            .border_color(gpui::rgba(0x7eb878ff))
                            .bg(gpui::white())
                            .child(
                                div()
                                    .absolute()
                                    .left(px(7.0))
                                    .top(px(1.0))
                                    .bottom(px(1.0))
                                    .w(px(1.0))
                                    .bg(gpui::rgba(0xb7d7b3ff)),
                            )
                            .child(
                                div()
                                    .absolute()
                                    .left(px(1.0))
                                    .right(px(1.0))
                                    .top(px(10.0))
                                    .h(px(1.0))
                                    .bg(gpui::rgba(0xb7d7b3ff)),
                            )
                            .child(
                                div()
                                    .absolute()
                                    .left(px(1.0))
                                    .right(px(1.0))
                                    .top(px(19.0))
                                    .h(px(1.0))
                                    .bg(gpui::rgba(0xb7d7b3ff)),
                            ),
                    )
                    .child(
                        div()
                            .absolute()
                            .left(px(5.0))
                            .top(px(10.0))
                            .size(px(22.0))
                            .rounded(px(2.0))
                            .bg(gpui::rgba(0x1f7244ff))
                            .flex()
                            .items_center()
                            .justify_center()
                            .text_size(px(12.0))
                            .font_weight(gpui::FontWeight(600.0))
                            .text_color(gpui::white())
                            .child("X"),
                    )
                    .child(extension_badge())
                    .into_any_element(),
            };
            let right = match index {
                1 => div()
                    .flex()
                    .items_center()
                    .gap(px(10.0))
                    .child(self.small_button(crate::i18n::text("管理"), false, theme))
                    .child(self.switch_control(true, (page.slug, 0, index), theme, cx))
                    .into_any_element(),
                2 => div()
                    .text_color(theme.text_tertiary)
                    .child("›")
                    .into_any_element(),
                _ => self.control(row.control, (page.slug, 0, index), theme, cx),
            };
            apps = apps.child(
                div()
                    .h(px(64.0))
                    .px(px(16.0))
                    .relative()
                    .flex()
                    .items_center()
                    .gap(px(12.0))
                    .when(index < 3, |node| {
                        node.child(
                            div()
                                .absolute()
                                .bottom_0()
                                .left(px(16.0))
                                .right(px(16.0))
                                .h(px(1.0))
                                .bg(theme.border),
                        )
                    })
                    .child(icon)
                    .child(
                        div()
                            .min_w(px(0.0))
                            .flex_1()
                            .flex()
                            .flex_col()
                            .gap(px(2.0))
                            .child(
                                div()
                                    .text_size(px(13.0))
                                    .line_height(px(18.5714))
                                    .font_weight(gpui::FontWeight(500.0))
                                    .child(crate::i18n::text(row.title)),
                            )
                            .child(
                                div()
                                    .text_size(px(12.0))
                                    .line_height(px(16.0))
                                    .text_color(theme.settings_description)
                                    .child(crate::i18n::text(row.subtitle)),
                            ),
                    )
                    .child(right),
            );
        }
        let lock = &rows[4];
        div()
            .w_full()
            .max_w(px(768.0))
            .mx_auto()
            .pt(px(66.0))
            .pb(px(80.0))
            .child(
                div()
                    .text_size(px(24.0))
                    .line_height(px(28.8))
                    .font_weight(gpui::FontWeight::NORMAL)
                    .child(crate::i18n::text(page.label)),
            )
            .child(
                div()
                    .mt(px(6.0))
                    .text_size(px(14.0))
                    .line_height(px(21.0))
                    .text_color(theme.settings_description)
                    .child(crate::i18n::text(page.intro)),
            )
            .child(
                div()
                    .mt(px(41.5))
                    .text_size(px(14.0))
                    .line_height(px(21.0))
                    .font_weight(gpui::FontWeight(500.0))
                    .child(crate::i18n::text("控制")),
            )
            .child(apps)
            .child(
                div()
                    .mt(px(6.0))
                    .h(px(66.0))
                    .px(px(16.0))
                    .rounded(px(20.0))
                    .border_1()
                    .border_color(theme.border)
                    .bg(theme.settings_panel)
                    .flex()
                    .items_center()
                    .gap(px(12.0))
                    .child(
                        div()
                            .size(px(40.0))
                            .relative()
                            .child(
                                div()
                                    .absolute()
                                    .left(px(7.0))
                                    .top(px(8.0))
                                    .w(px(23.0))
                                    .h(px(16.0))
                                    .rounded(px(1.5))
                                    .border_1()
                                    .border_color(gpui::rgba(0x33414aff))
                                    .bg(gpui::rgba(0x68a9dcff)),
                            )
                            .child(
                                div()
                                    .absolute()
                                    .left(px(5.0))
                                    .top(px(24.0))
                                    .w(px(27.0))
                                    .h(px(2.0))
                                    .rounded(px(1.0))
                                    .bg(gpui::rgba(0x485159ff)),
                            )
                            .child(
                                div()
                                    .absolute()
                                    .left(px(25.0))
                                    .top(px(20.0))
                                    .w(px(10.0))
                                    .h(px(10.0))
                                    .rounded(px(1.5))
                                    .bg(gpui::rgba(0xc7a36bff))
                                    .child(
                                        div()
                                            .absolute()
                                            .left(px(2.0))
                                            .top(px(-5.0))
                                            .w(px(6.0))
                                            .h(px(7.0))
                                            .rounded_t(px(4.0))
                                            .border_1()
                                            .border_color(gpui::rgba(0x8f7654ff)),
                                    ),
                            ),
                    )
                    .child(
                        div()
                            .flex_1()
                            .flex()
                            .flex_col()
                            .gap(px(2.0))
                            .child(
                                div()
                                    .text_size(px(13.0))
                                    .line_height(px(18.5714))
                                    .font_weight(gpui::FontWeight(500.0))
                                    .child(crate::i18n::text(lock.title)),
                            )
                            .child(
                                div()
                                    .text_size(px(12.0))
                                    .line_height(px(16.0))
                                    .text_color(theme.settings_description)
                                    .child(crate::i18n::text(lock.subtitle)),
                            ),
                    )
                    .child(self.switch_control(false, (page.slug, 0, 4), theme, cx)),
            )
            .child(
                div()
                    .mt(px(49.5))
                    .text_size(px(14.0))
                    .line_height(px(21.0))
                    .font_weight(gpui::FontWeight(500.0))
                    .child(crate::i18n::text("始终允许的应用")),
            )
            .child(
                div()
                    .mt(px(15.5))
                    .h(px(66.0))
                    .rounded(px(20.0))
                    .border_1()
                    .border_color(theme.border)
                    .bg(theme.settings_panel)
                    .flex()
                    .items_center()
                    .justify_center()
                    .text_size(px(13.0))
                    .line_height(px(18.5714))
                    .text_color(theme.settings_description)
                    .child(crate::i18n::text("暂无")),
            )
            .into_any_element()
    }
}
